const UI = {"en": {"roleLine": "CREATIVE TECHNOLOGIST / COMPUTATIONAL DESIGNER", "about": "[ ABOUT ]", "themeLight": "[ LIGHT ]", "themeDark": "[ DARK ]", "index": "[ INDEX ]", "lang": "[ EN / 中文 ]", "footerLeft": "ACGT / SELECTED WORK", "footerRight": "MUTATION → DECODE", "close": "[ ESC / CLOSE ]", "labels": {"role": "Role", "tools": "Tools", "output": "Output", "year": "Year"}, "story": {"question": "01 / Question", "built": "02 / Built", "judgement": "03 / Judgement"}, "taste": "Taste / Decision Log", "next": "NEXT MUTATION", "indexTitle": "PROJECT INDEX", "indexIntro": "A selection of projects and studies positioned between computational design, interface thinking, AI-assisted prototyping and visual judgement. The Genome interface remains the primary navigation: each mutation is a project entry point.", "aboutTitle": "ABOUT / PRACTICE", "aboutLead": "I work at the intersection of design, tools and judgement — building systems, interfaces and visual work that translate complexity into something legible, usable and felt.", "aboutText": "My background is in computational design, but my practice increasingly sits between creative technology, AI-native prototyping, product thinking and visual editing. I am interested in how tools shape attention, and how taste can be articulated through what is kept, removed and refined.", "aboutBlocks": [["Current", "Computational Designer<br>Bates Smart / Melbourne"], ["Working with", "Claude Code · Codex · ChatGPT · HTML/CSS/JS · Python · Rhino · Grasshopper · Mapbox · Revit"], ["Interested in", "AI-native interaction · model evaluation · multimodal interfaces · visual systems · generative tools · creative technology"], ["Contact", "<a class=\"contact-link\" href=\"mailto:zhanghangge@gmail.com\">zhanghangge@gmail.com</a><br>Beijing / Melbourne"]], "galleryTitle": "Selected Frames"}, "zh": {"roleLine": "创意技术 / 计算设计", "about": "[ 关于 ]", "themeLight": "[ 浅色 ]", "themeDark": "[ 深色 ]", "index": "[ 索引 ]", "lang": "[ 中文 / EN ]", "footerLeft": "ACGT / 作品索引", "footerRight": "变异 → 解码", "close": "[ ESC / 关闭 ]", "labels": {"role": "角色", "tools": "工具", "output": "产出", "year": "年份"}, "story": {"question": "01 / 问题", "built": "02 / 构建", "judgement": "03 / 判断"}, "taste": "审美判断 / 决策记录", "next": "下一个变异", "indexTitle": "项目索引", "indexIntro": "这些项目与研究分布在计算设计、界面思维、AI 辅助原型与视觉判断之间。Genome 仍然是主要导航方式：每一个 mutation 都是一个项目入口。", "aboutTitle": "关于 / 实践", "aboutLead": "我的工作位于设计、工具与判断的交叉处——通过系统、界面与视觉表达，把复杂性转化成可理解、可使用、可感知的体验。", "aboutText": "我的背景来自计算设计，但现在的实践越来越多地处在创意技术、AI 原型、产品思维与视觉编辑之间。我关心工具如何塑造注意力，也关心“审美”如何通过保留、删除与打磨被明确表达出来。", "aboutBlocks": [["当前", "Computational Designer<br>Bates Smart / 墨尔本"], ["使用中", "Claude Code · Codex · ChatGPT · HTML/CSS/JS · Python · Rhino · Grasshopper · Mapbox · Revit"], ["关注方向", "AI 原生交互 · 模型评估 · 多模态界面 · 视觉系统 · 生成工具 · 创意技术"], ["联系", "<a class=\"contact-link\" href=\"mailto:zhanghangge@gmail.com\">zhanghangge@gmail.com</a><br>北京 / 墨尔本"]], "galleryTitle": "摄影选帧"}};
let PROJECTS=[];
let PHOTO_DATA=null;
const L="ACGT", genome=document.getElementById("genome");
let zones=[], currentProject=0, lang=localStorage.getItem('garry_portfolio_lang')||'en';

async function loadData(){
  const [projectsRes, photoRes] = await Promise.all([fetch('data/projects.json'), fetch('data/photography.json')]);
  if(!projectsRes.ok || !photoRes.ok) throw new Error('Portfolio data failed to load.');
  PROJECTS = await projectsRes.json();
  PHOTO_DATA = await photoRes.json();
}
function t(){return UI[lang]}
function seq(n){let s="";for(let i=0;i<n;i++)s+=L[Math.random()*4|0];return s}
function proj(i){return PROJECTS[i][lang]}
function cells(s,mutationAt=-1,p=-1){return [...s].map((ch,i)=>`<span class="cell ${i===mutationAt?"mutation":""}" ${i===mutationAt?`data-p="${p}" tabindex="0" role="button" aria-label="Decode project ${PROJECTS[p]?.[lang]?.title||""}"`:""}>${ch}</span>`).join("")}
function mutationRows(count,total){const top=2,bottom=Math.max(top,count-3),span=Math.max(1,bottom-top);return Array.from({length:total},(_,i)=>Math.round(top+(span*(i/Math.max(1,total-1)))));}
function build(){genome.innerHTML="";zones=[];const mobile=innerWidth<700,rowH=mobile?31:34;const count=Math.max(12,Math.floor((innerHeight-(mobile?142:136))/rowH));const chars=Math.ceil(innerWidth/(mobile?13:15))+45;const positions=mutationRows(count,PROJECTS.length);let projectCursor=0;for(let r=0;r<count;r++){const row=document.createElement("div");row.className="row";const s=seq(chars);let mut=-1,p=-1;if(projectCursor<PROJECTS.length && r===positions[projectCursor]){p=projectCursor++;mut=12+(r*11)%(Math.max(18,chars-28));row.classList.add("zone");row.dataset.p=p;}const track=document.createElement("div");track.className="track";track.innerHTML=cells(s,mut,p)+cells(s,-1,-1);row.appendChild(track);if(p>=0){const d=document.createElement("div");d.className="decode";d.dataset.p=p;d.setAttribute("role","button");d.tabIndex=0;d.innerHTML=`<div class="line title"></div><div class="line brief"></div><div class="line meta"></div><div class="line year"></div>`;row.appendChild(d);zones.push(row);}genome.appendChild(row);}bind();}
function flipLine(el,target,delay=0){const chars="ACGT";let step=0,max=8;const timer=setInterval(()=>{step++;let out="";for(let i=0;i<target.length;i++){if(target[i]===" "){out+=" ";continue}const settle=Math.floor((i/Math.max(1,target.length))*4)+3;out+=step>=settle?target[i]:chars[Math.random()*4|0];}el.textContent=out;if(step>=max){el.textContent=target;clearInterval(timer)}},72+delay*2);}
function activate(row){zones.forEach(z=>{if(z!==row)z.classList.remove("active")});row.classList.add("active");const p=proj(+row.dataset.p),d=row.querySelector('.decode');flipLine(d.querySelector('.title'),`${PROJECTS[+row.dataset.p].id} / ${p.title}`);flipLine(d.querySelector('.brief'),p.brief,4);flipLine(d.querySelector('.meta'),p.meta,7);flipLine(d.querySelector('.year'),p.year,10);}
function bind(){document.querySelectorAll('.mutation').forEach(m=>{const row=m.closest('.zone');m.addEventListener('mouseenter',()=>activate(row));m.addEventListener('focus',()=>activate(row));m.addEventListener('click',e=>{e.stopPropagation();activate(row)});});zones.forEach(row=>{row.addEventListener('mouseleave',()=>row.classList.remove('active'));const d=row.querySelector('.decode');d.addEventListener('mouseenter',()=>row.classList.add('active'));d.addEventListener('click',()=>openProject(+row.dataset.p));d.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openProject(+row.dataset.p)}});});}
const projectEl=document.getElementById('project'),indexPanel=document.getElementById('indexPanel'),aboutPanel=document.getElementById('aboutPanel');
const pid=document.getElementById('pid'),pt=document.getElementById('pt'),pd=document.getElementById('pd'),pbrief=document.getElementById('pbrief');
const prole=document.getElementById('prole'),ptools=document.getElementById('ptools'),poutput=document.getElementById('poutput'),pyear=document.getElementById('pyear');
const pquestion=document.getElementById('pquestion'),pbuilt=document.getElementById('pbuilt'),pjudgement=document.getElementById('pjudgement'),pmedia=document.getElementById('pmedia'),ptaste=document.getElementById('ptaste'),nextProjectName=document.getElementById('nextProjectName');
const photoWallWrap=document.getElementById('photoWallWrap'),photoWall=document.getElementById('photoWall');
function hidePanels(){[projectEl,indexPanel,aboutPanel].forEach(el=>{el.classList.remove('visible');el.setAttribute('aria-hidden','true')});document.body.style.overflow='hidden';}
function showPanel(el){hidePanels();el.classList.add('visible');el.setAttribute('aria-hidden','false');el.scrollTop=0;}
function renderPhotoWall(){if(!PHOTO_DATA?.photos?.length){photoWallWrap.classList.remove('visible');photoWall.innerHTML='';return;}photoWallWrap.classList.add('visible');document.getElementById('photoNote').textContent=PHOTO_DATA.note[lang];document.getElementById('galleryTitle').textContent=t().galleryTitle;photoWall.innerHTML=PHOTO_DATA.photos.map((item,idx)=>`<figure class="photo-item"><img src="${item.src}" srcset="${item.srcset.small} 640w, ${item.srcset.medium} 1400w, ${item.srcset.large} 2048w" sizes="(max-width:700px) 100vw, (max-width:900px) 50vw, 33vw" loading="${idx<2?'eager':'lazy'}" decoding="async" width="${item.width}" height="${item.height}" alt="${item.caption[lang]}"><figcaption class="photo-cap"><span><b>${item.id}</b></span><span>${item.visibleMeta?item.caption[lang]:''}</span></figcaption></figure>`).join('');}
function openProject(i){currentProject=i;const p=proj(i),base=PROJECTS[i];pid.textContent=`MUTATION ${base.id}`;pt.textContent=p.title;pd.textContent=p.desc;pbrief.textContent=p.brief;prole.textContent=p.role;ptools.textContent=p.tools;poutput.textContent=p.output;pyear.textContent=p.year;pquestion.textContent=p.question;pbuilt.textContent=p.built;pjudgement.textContent=p.judgement;pmedia.innerHTML=p.media.map((m,j)=>`<div class="media"><span><b>${String(j+1).padStart(2,'0')}</b></span><span>${m}</span></div>`).join('');ptaste.innerHTML=p.taste.map(item=>`<div class="taste-item"><span class="taste-key">${item[0]}</span><p>${item[1]}</p></div>`).join('');if(base.id==='06')renderPhotoWall();else{photoWallWrap.classList.remove('visible');photoWall.innerHTML='';}const next=proj((i+1)%PROJECTS.length),nextBase=PROJECTS[(i+1)%PROJECTS.length];nextProjectName.textContent=`${nextBase.id} / ${next.title}`;showPanel(projectEl);}
function buildIndex(){const list=document.getElementById('indexList');list.innerHTML=PROJECTS.map((p,i)=>{const q=p[lang];return `<button class="index-row" data-project="${i}"><span class="index-no">${p.id}</span><span class="index-title">${q.title}</span><span class="index-meta">${q.meta}</span><span class="index-year">${q.year}</span></button>`}).join('');list.querySelectorAll('.index-row').forEach(btn=>btn.addEventListener('click',()=>openProject(+btn.dataset.project)));}
function renderAbout(){const copy=t();document.getElementById('aboutHero').textContent=copy.aboutTitle;document.getElementById('aboutLead').textContent=copy.aboutLead;document.getElementById('aboutText').textContent=copy.aboutText;document.getElementById('aboutAside').innerHTML=copy.aboutBlocks.map(block=>`<div class="about-block"><h2>${block[0]}</h2><p>${block[1]}</p></div>`).join('');}
function applyUI(){const copy=t();document.documentElement.lang=lang==='en'?'en':'zh-CN';document.getElementById('brandRole').textContent=copy.roleLine;document.getElementById('about').textContent=copy.about;document.getElementById('theme').textContent=document.body.classList.contains('light')?copy.themeDark:copy.themeLight;document.getElementById('index').textContent=copy.index;document.getElementById('langToggle').textContent=copy.lang;document.getElementById('footerLeft').textContent=copy.footerLeft;document.getElementById('footerRight').textContent=copy.footerRight;document.getElementById('close').textContent=copy.close;document.getElementById('indexClose').textContent=copy.close;document.getElementById('aboutClose').textContent=copy.close;document.getElementById('labelRole').textContent=copy.labels.role;document.getElementById('labelTools').textContent=copy.labels.tools;document.getElementById('labelOutput').textContent=copy.labels.output;document.getElementById('labelYear').textContent=copy.labels.year;document.getElementById('storyQuestion').textContent=copy.story.question;document.getElementById('storyBuilt').textContent=copy.story.built;document.getElementById('storyJudgement').textContent=copy.story.judgement;document.getElementById('tasteHeading').textContent=copy.taste;document.getElementById('nextLabel').textContent=copy.next;document.getElementById('indexTitle').textContent=copy.indexTitle;document.getElementById('indexIntro').textContent=copy.indexIntro;document.getElementById('aboutTitle').textContent=copy.aboutTitle;renderAbout();buildIndex();build();if(projectEl.classList.contains('visible'))openProject(currentProject);}
function bindGlobal(){document.getElementById('close').addEventListener('click',hidePanels);document.querySelectorAll('.panelClose').forEach(btn=>btn.addEventListener('click',hidePanels));document.getElementById('nextProject').addEventListener('click',()=>openProject((currentProject+1)%PROJECTS.length));document.getElementById('theme').addEventListener('click',e=>{document.body.classList.toggle('light');e.currentTarget.textContent=document.body.classList.contains('light')?t().themeDark:t().themeLight;});document.getElementById('index').addEventListener('click',()=>showPanel(indexPanel));document.getElementById('about').addEventListener('click',()=>showPanel(aboutPanel));document.getElementById('langToggle').addEventListener('click',()=>{lang=lang==='en'?'zh':'en';localStorage.setItem('garry_portfolio_lang',lang);applyUI();});addEventListener('keydown',e=>{if(e.key==='Escape')hidePanels()});let rt;addEventListener('resize',()=>{clearTimeout(rt);rt=setTimeout(build,150)});}
try{await loadData();bindGlobal();applyUI();}catch(err){console.error(err);document.body.innerHTML='<pre style="padding:24px;color:white;background:#050505">Portfolio data failed to load. Serve this folder over HTTP (for example Vercel or a local development server).</pre>';}
