import {drawEditorialDiagram,refineFacadeDiagrams} from '../js/diagrams.js';
import {drawEditorialDiagram as draftDiagram} from '../bts/evidence/draft.js';
import {drawEditorialDiagram as reviewedDiagram} from '../bts/evidence/reviewed.js';
import {renderTODAIPrintSVG} from './workflow-static.js';
import {defaults,metrics,bestLocation} from '../js/todai-model.js';
const portfolio=document.getElementById('portfolio'),status=document.getElementById('status'),printButton=document.getElementById('printButton');
const PAGES=[],escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const image=(src,caption,cover=false)=>'<figure class="'+(cover?'cover':'')+'"><img src="'+src+'" alt="'+escape(caption)+'"><figcaption>'+caption+'</figcaption></figure>';
const arch=(name,caption)=>image('/assets/architecture/'+name+'.webp',caption);
const diagram=(category,stage,caption)=>'<figure class="process-fig"><canvas data-category="'+category+'" data-stage="'+stage+'"></canvas><figcaption>'+caption+'</figcaption></figure>';
function page(category,title,deck,body,note=''){PAGES.push({category,title,deck,body,note});}
let seed=27;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
function cover(){
 const marks={3:['SPACE / 建筑设计',28],5:['SYSTEM / 信息与城市',16],8:['CODE / 计算设计',35],12:['OBSERVATION / 摄影',20],16:['RESEARCH / TODAI',31]};
 const rows=Array.from({length:21},(_,i)=>{const letters=Array.from({length:155},()=> 'ACGT'[Math.floor(rnd()*4)]);const mark=marks[i];return '<div class="genome-row">'+(mark?letters.slice(0,mark[1]).join(' ')+'<span class="genome-mutation">'+mark[0]+'</span>'+letters.slice(mark[1]+8).join(' '):letters.join(' '))+'</div>';}).join('');
 return '<div class="cover-top"><div class="cover-brand">GARRY ZHANG<span class="cover-role">CREATIVE TECHNOLOGIST / COMPUTATIONAL DESIGNER</span></div><div class="cover-nav">[ 作品集 / PORTFOLIO ]　[ 2026 ]</div></div><div class="genome-cover">'+rows+'</div><div class="cover-index">GENOME / SELECTED WORK<br>ACGT → MUTATION → DECODE</div><div class="cover-bottom"><div><strong>SELECTED WORK</strong>建筑 · 计算设计 · 信息系统 · 摄影 · 研究</div><div><a href="https://www.changhangko.cc/">CHANGHANGKO.CC ↗</a><br>MELBOURNE / AUSTRALIA</div></div>';
}
async function build(){
 const [source,photos]=await Promise.all([fetch('/index.html',{cache:'no-store'}).then(r=>r.text()),fetch('/data/photography.json').then(r=>r.json())]);
 const web=new DOMParser().parseFromString(source,'text/html');
 const photo=(id)=>{const p=photos.photos.find(p=>p.id==='06.'+String(id).padStart(3,'0'));return image('/'+(p.srcset.large||p.src),p.id+' / '+p.caption.zh);};
 PAGES.push({cover:true,category:'COVER',title:'Genome / Garry Zhang',body:cover()});
 page('01 / SPACE / BATES SMART / 2025','60 Denmark Street','住宅总体规划：通过体量、日照与公共空间的比较，形成南北向体块和北向开放空间。',
 '<div class="stack" style="grid-template-rows:465px 1fr"><div class="two-columns" style="grid-template-columns:1.75fr 1fr">'+arch('denmark-hero','PUBLIC OPEN SPACE / KEW, MELBOURNE')+'<div class="stack" style="grid-template-rows:1fr 1fr">'+arch('denmark-solar','SOLAR ANALYSIS / GRASSHOPPER + LADYBUG')+arch('denmark-massing','MASSING / HEIGHT + ORIENTATION')+'</div></div><div class="two-columns" style="grid-template-columns:1fr 1.4fr">'+arch('denmark-model','PHYSICAL MODEL / PUBLIC REALM')+'<div><div class="metrics"><div class="metric"><strong>90%</strong><span>住宅冬季直接日照</span></div><div class="metric"><strong>5h+</strong><span>主要公共空间直接日照</span></div></div><p class="note">参与设计、参数化分析与视觉表达。日照数字来自团队提交方案，反映方案表现。</p></div></div></div>','团队协作项目 / 原始方案图像与分析');
 page('01 / SPACE / PUBLIC REALM','Street scale / 街道尺度','三至五层街墙衔接高层体量；地面通行与开放空间同时参与建筑形态的推敲。',
 '<div class="two-columns" style="grid-template-columns:1.2fr 1fr"><div class="stack" style="grid-template-rows:480px 1fr">'+arch('denmark-street','DENMARK STREET / HUMAN-SCALE STREET EDGE')+arch('denmark-section','SECTION / 3–5 STOREY STREETWALL')+'</div><div class="diagram-grid">'+[0,1,2,3].map((i)=>diagram('space',i,['建筑包络','保留通行','比较高度','建筑与开放空间'][i])).join('')+'</div></div>','右侧为网页设计过程示意，非项目实测几何');
 page('01 / SPACE / SELECTED PROFESSIONAL WORK','Iglu Arden','通过重复框架、进深、绿化与退台，形成两栋相互关联、又各有区别的建筑。',
 '<div class="two-columns" style="grid-template-columns:.8fr 1.6fr">'+arch('arden-tower','TOWER SOUTH ELEVATION')+'<div class="stack" style="grid-template-rows:1fr 130px">'+arch('arden-facade-matrix','FAÇADE EXPRESSION / PODIUM STUDIES')+'<div class="project-note"><p>可行性与立面研究，比较比例、重复构件和垂直节奏。</p><span>BATES SMART<br>TEAM PROJECT / FAÇADE STUDY</span></div></div></div>','团队协作项目 / 立面系统与视觉表达');
 page('01 / SPACE / COMPETITION STUDY','87 Queensbridge / OSK','三角形塔楼在视野、阴影和风环境之间进行比较，围绕核心筒组织三个外围区域。',
 '<div class="two-columns" style="grid-template-columns:1fr 1.45fr">'+arch('osk-hero','ARTICULATED FORM / ASCENDING COMPOSITION')+'<div class="stack" style="grid-template-rows:1.3fr 1fr">'+arch('osk-principles','VIEWS / SHADOWS / GROUND PLANE')+arch('osk-whole','TRIANGULAR TOWER / WHOLE DEVELOPMENT')+'</div></div>','BATES SMART / 团队协作竞赛方案');
 page('02 / SYSTEM / INFORMATION ARCHITECTURE','Studio Library','从“文件放在哪里”转向“设计任务需要什么”：城市模型、材质、立面和颜色统一到可查找的入口。',
 '<div class="two-columns" style="grid-template-columns:1.7fr .85fr">'+image('/print/web-assets/studio-home.jpg','LIVE WEB INTERFACE / PUBLIC DEMONSTRATION')+'<div class="stack" style="grid-template-rows:290px 290px 1fr">'+diagram('system',0,'BEFORE / 资源分散')+diagram('system',2,'AFTER / 从任务出发')+'<div class="project-note"><p>参与信息架构、界面设计与前端原型。当前正向墨尔本办公室同事部署试用。</p></div></div></div>','公开界面使用示例资源 / 专有资料未展示');
 page('02 / SYSTEM / INTERFACE DETAILS','Find / inspect / compare','搜索、筛选、资源详情与颜色比较，在同一套界面中支持设计查找。',
 '<div class="stack" style="grid-template-rows:650px 1fr"><div class="two-columns" style="grid-template-columns:1fr 1fr">'+image('/print/web-assets/studio-materials.jpg','ENSCAPE MATERIALS / SEARCH + FILTER')+image('/print/web-assets/studio-palette.jpg','COLOUR PALETTE / INSPECT + COPY')+'</div><div class="project-note"><p>Rhino Tabs 自动分发到建筑师电脑，减少查找工具与信息时的沟通。City Model 当前覆盖墨尔本大都会区和悉尼 CBD。</p><span>INTERNAL TOOLING + CITY DATA<br><a href="https://www.changhangko.cc/?project=system">打开系统项目 ↗</a></span></div></div>','部署进行中 / 未将示例数量作为实际使用数据');
 const facade=web.querySelector('.parametric-process-row').cloneNode(true);facade.className='facade-print';facade.querySelectorAll('[data-zh]').forEach(e=>e.textContent=e.dataset.zh);
 page('03 / CODE / BUILT FAÇADE / MELBOURNE','435 Bourke Street','把曲面 PV 外立面转化为可重复的 Grasshopper 流程，生成独立面板几何，供设计深化与施工图使用。',
 '<div class="two-columns" style="grid-template-columns:.78fr 1.4fr">'+image('/assets/parametric/435-bourke-highlight.jpg','BUILT RESULT / PV FAÇADE HIGHLIGHT')+'<div class="stack" style="grid-template-rows:335px 340px 78px">'+facade.outerHTML+image('/assets/parametric/435-bourke-grasshopper-script.jpg','ORIGINAL GRASSHOPPER DEFINITION / 实际工作脚本')+'<div class="project-note"><p>Rhino → Grasshopper → Panel Geometry → Documentation</p><span>七个步骤使用同一组曲线<br>流程重建示意，非加工几何</span></div></div></div>','参与工作 / 计算设计、工作流调整与面板几何');
 page('03 / CODE / AI-ASSISTED BUILD','Generate / critique / revise','以这份网页为实际案例：给出建筑参考，检查生成结果，再针对图层、路径与可读性作出修改。',
 '<div class="stack" style="grid-template-rows:490px 1fr"><div class="two-columns" style="grid-template-columns:1fr 1fr"><figure class="process-fig"><canvas data-audit="draft"></canvas><figcaption>GENERATED / 原始生成版本</figcaption></figure><figure class="process-fig"><canvas data-audit="reviewed"></canvas><figcaption>REVIEWED / 图层修正版本</figcaption></figure></div><div class="three-grid"><div><p class="kicker">01 / BRIEF</p><p class="note">参考建筑轴测图解，采用低饱和色彩，使图解释设计过程。</p></div><div><p class="kicker">02 / REVIEW</p><p class="note">检查路径是否穿过体量、底板与建筑的前后关系，以及文字与引线的冲突。</p></div><div><p class="kicker">03 / REVISION</p><p class="note">修正绘制顺序，让路径保持在地面；统一线重、色彩与标注。</p><p class="minor" style="margin-top:20px"><a href="https://www.changhangko.cc/bts/">设计规则与实际版本记录 ↗</a></p></div></div></div>','设计方向与参考由 Garry 提供；实现检查与修改由 Codex 辅助完成');
 const concept=web.querySelector('.td-map').cloneNode(true);concept.className='tod-concept';concept.querySelectorAll('[data-zh]').forEach(e=>e.textContent=e.dataset.zh);
 page('04 / RESEARCH / 本科毕业论文 / UNSW / 2021–22','TODAI','公共交通导向开发辅助界面：把城市输入、参数化生成、优化与 H2O / XGBoost 预测连接起来。',
 '<div class="stack" style="grid-template-rows:315px 1fr"><div class="two-columns" style="grid-template-columns:1fr 1fr">'+concept.outerHTML+'<div><p class="kicker">TRANSIT-ORIENTED DEVELOPMENT</p><h2 style="font-size:38px;line-height:1.3;font-weight:400;margin-bottom:20px">距离由街道决定，<br>规划需要比较方案。</h2><p class="note">以悉尼 Five Dock 拟建地铁站为研究案例，比较步行性、密度、设施位置与建筑形态。</p></div></div><div class="workflow-six">'+[0,1,2,3,4,5].map((i)=>'<figure>'+renderTODAIPrintSVG(i,'zh')+'</figure>').join('')+'</div></div>','图解解释原始研究流程，不展示训练精度或实测结果');
 const best=bestLocation(),base=metrics(defaults),current=metrics({...defaults,amenity:best.id});
 page('04 / RESEARCH / INTERACTIVE RECONSTRUCTION','TODAI / Live study','移动设施位置，浏览器重新计算住宅到设施的最短路径，并比较方案指标。',
 '<div class="study-layout"><div id="print-study-drawings" class="study-images"></div><div class="baseline-comparison"><p class="kicker">BASELINE → COMPARISON</p><h2>400 m → 300 m</h2><table><thead><tr><th>指标</th><th>基准</th><th>比较方案</th></tr></thead><tbody><tr><td>平均步行距离</td><td>'+base.mean+' m</td><td>'+current.mean+' m</td></tr><tr><td>平均步行时间</td><td>'+base.time+' min</td><td>'+current.time+' min</td></tr><tr><td>住宅建筑面积</td><td>28,800 m²</td><td>28,800 m²</td></tr></tbody></table><p class="note">示意网络包含 20 个路口，每段街道 100 米。位置搜索逐个比较路口，以四处住宅的平均步行距离最小为目标。</p><p class="minor" style="margin-top:22px">2026 年网页交互重建；非原始 TODAI 模型、Five Dock 实测数据或 XGBoost 预测。步行速度假设为 80 米/分钟。</p><p style="margin-top:26px;font-size:16px"><a href="https://papers.cumincad.org/data/works/att/caadria2022_264.pdf">阅读论文 / CAADRIA 2022 ↗</a></p></div></div>','参与工作 / 研究、计算设计与可视化');
 page('05 / OBSERVATION / PHOTOGRAPHY','Photography / 摄影','跨年份精选；以画面之间的密度、距离和几何关系组织观看顺序。',
 '<div class="photo-pair">'+photo(1)+'<div class="stack">'+photo(2)+photo(3)+photo(19)+'</div></div>','MEDIUM FORMAT / 135 FILM / DIGITAL');
 page('05 / OBSERVATION / SELECTED FRAMES','Distance / light / trace','从普通的场景中选择值得停留的画面，让相邻照片产生新的联想。',
 '<div class="contact-sheet">'+[4,7,8,13,15,12].map(photo).join('')+'</div>','PHOTOGRAPHY + SEQUENCING / <a href="https://www.instagram.com/changhangko/">@changhangko ↗</a>');
 portfolio.innerHTML=PAGES.map((p,i)=>'<div class="page-wrap" data-page="'+(i+1)+'"><article class="sheet '+(p.cover?'cover-sheet':'')+'">'+(p.cover?p.body:'<div class="sheet-head"><p class="kicker">'+p.category+'</p><h1>'+p.title+'</h1><p class="sheet-deck">'+p.deck+'</p></div><div class="sheet-content">'+p.body+'</div><div class="sheet-footer"><span>'+p.note+'</span><a href="https://www.changhangko.cc/">CHANGHANGKO.CC / '+String(i+1).padStart(2,'0')+' / '+PAGES.length+'</a></div>')+'</article></div>').join('');
 const capture=Number(new URLSearchParams(location.search).get('page'));if(capture){document.body.classList.add('capture-mode');document.querySelector('[data-page="'+capture+'"]').classList.add('selected');}
 const resize=()=>{const scale=capture?innerWidth/1600:Math.min(1,(innerWidth-48)/1600);document.querySelectorAll('.page-wrap').forEach(e=>{e.style.width=1600*scale+'px';e.style.height=1131.429*scale+'px';e.firstElementChild.style.transform='scale('+scale+')';});draw();};
 function draw(){document.querySelectorAll('canvas[data-category]').forEach(c=>drawEditorialDiagram(c,c.dataset.category,Number(c.dataset.stage),1,photos.photos,'zh'));document.querySelectorAll('canvas[data-audit]').forEach(c=>(c.dataset.audit==='draft'?draftDiagram:reviewedDiagram)(c,'space',3,1,[],'zh'));}
 refineFacadeDiagrams(portfolio);
 const parked=document.createElement('section');parked.id='todaiPlayground';parked.style.display='none';document.body.append(parked);await import('../js/todai-playground.js');parked.querySelector('#tp-search').click();document.getElementById('print-study-drawings').innerHTML=parked.querySelector('.tp-drawings').outerHTML+'<p class="minor">20 JUNCTIONS / DIJKSTRA SHORTEST PATH / 6 STOREYS</p>';parked.remove();
 await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode().catch(()=>null)));resize();window.addEventListener('resize',resize);
 document.body.dataset.ready='true';status.textContent=PAGES.length+' PAGES / A3 LANDSCAPE / WEB EDITION';printButton.disabled=false;printButton.onclick=()=>window.print();
}
build().catch(e=>{status.textContent=e.message;console.error(e)});
